name: CI Build Check

on:
  push:
    branches: [ "v2.0.0-dev", "master" ]
  pull_request:
    branches: [ "v2.0.0-dev", "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    environment:
      name: IMAGESHARP_LICENSE_ID

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'
          cache: 'pip'

      - name: Build C# Generator
        shell: bash
        run: |
          python -c "import os; lic = r'${{ secrets.IMAGESHARP_LICENSE_ID }}'; open('sixlabors.lic', 'w').write(lic) if lic else None"
          dotnet build generator -c Release

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          python-flags: -m src
          mode: app
          output-dir: build
          user-package-configuration-file: mcskybuilder.nuitka-package.config.yml
          enable-plugins: tk-inter

      - name: Upload CI Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-CI-Build
          path: build/**/*
